name: Continuous Integration

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  test-action:
    strategy:
      matrix:
        os:
        - ubuntu-latest
        - macos-latest
        # - windows-latest # need to build Windows binaries

    name: GitHub Actions Test
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Test Local Action
        id: test-action
        uses: ./
        with:
          access_token: ${{ secrets.BWS_ACCESS_TOKEN }}
          secrets: |
            cdc0a886-6ad6-4136-bfd4-b04f01149173 > SECRET_ONE
            2b0da64f-f40d-434a-ad94-afdb01269ea9 > COMPARE_FILE
            a668b804-781c-4864-8a49-b0500013b413 > GIGACHAD
            3865c716-4e4f-4d19-9be5-b2d1015fb57c > FERRIS
          cloud_region: us
          # base_url: "https://vault.bitwarden.com"
          # # identity_url: "https://identity.bitwarden.com"
          # # api_url: "https://api.bitwarden.com"

      - name: Print Output from Rust sm-action
        id: output
        run: |
          echo the following secrets should be masked:
          echo "SECRET_ONE=$SECRET_ONE"
          echo "COMPARE_FILE=$COMPARE_FILE"
          echo "GIGACHAD=$GIGACHAD"
          echo "FERRIS=$FERRIS"
          echo

          echo the following secrets should not be masked:
          echo "$SECRET_ONE" | sed 's/./& /g'
          echo "$COMPARE_FILE" | sed 's/./& /g'
          echo "$GIGACHAD" | sed 's/./& /g'
          echo "$FERRIS" | sed 's/./& /g'
          echo

      - name: Test existing sm-action
        id: sm-action
        uses: bitwarden/sm-action@v2.2.0
        with:
          access_token: ${{ secrets.BWS_ACCESS_TOKEN }}
          secrets: |
            cdc0a886-6ad6-4136-bfd4-b04f01149173 > SECRET_ONE
            2b0da64f-f40d-434a-ad94-afdb01269ea9 > COMPARE_FILE
            a668b804-781c-4864-8a49-b0500013b413 > GIGACHAD
            3865c716-4e4f-4d19-9be5-b2d1015fb57c > FERRIS
          cloud_region: us

      - name: Print Output from existing sm-action
        run: |
          echo the following two secrets should be masked:
          echo "SECRET_ONE=$SECRET_ONE"
          echo "COMPARE_FILE=$COMPARE_FILE"
          echo "GIGACHAD=$GIGACHAD"
          echo "FERRIS=$FERRIS"
          echo

          echo the following two secrets should not be masked:
          echo "$SECRET_ONE" | sed 's/./& /g'
          echo "$COMPARE_FILE" | sed 's/./& /g'
          echo "$GIGACHAD" | sed 's/./& /g'
          echo "$FERRIS" | sed 's/./& /g'
          echo
